### ISSUE TITLE
Разобраться с фигурными скобками и if'ами

### ISSUE THREAD

**Issue by coursar** [Roman-code37/Taxi#2]
https://github.com/Roman-code37/Taxi/blob/488d89de82b3dfa0d73cf62e8cf40d1d3e0f8314/src/main/java/DistanceService.java#L10-L14

**Comment by Roman-code37** [comment]
разобрался со скобками и if

**Comment by coursar** [comment]
Для else всегда нужно ставить фигурные скобки (только если за else не идёт if)
